export const TOGGLE_CHAT = 'BEHAVIOR/TOGGLE_CHAT';
export const SET_INPUT_DISABLED = 'BEHAVIOR/SET_INPUT_DISABLED';
export const TOGGLE_INPUT_DISABLED = 'BEHAVIOR/TOGGLE_INPUT_DISABLED';
export const ADD_NEW_USER_MESSAGE = 'MESSAGES/ADD_NEW_USER_MESSAGE';
export const ADD_NEW_RESPONSE_MESSAGE = 'MESSAGES/ADD_NEW_RESPONSE_MESSAGE';
export const ADD_COMPONENT_MESSAGE = 'MESSAGES/ADD_COMPONENT_MESSAGE';
export const SET_MESSAGES = 'MESSAGES/SET_MESSAGES';
export const DROP_MESSAGES = 'MESSAGES/DROP_MESSAGES';
